### ISSUE TITLE
Error flag HAL_ADC_STATE_ERROR_INTERNAL checked but never set

### ISSUE THREAD

**Issue by vilesovds** [STMicroelectronics/stm32f2xx_hal_driver#1]
**Description**
At line https://github.com/STMicroelectronics/stm32f2xx_hal_driver/blob/master/Src/stm32f2xx_hal_adc.c#L370 (just example) flag `HAL_ADC_STATE_ERROR_INTERNAL` checked

I looked in all the files and realized that it is not setting anywhere

**Screenshots**
![image](https://user-images.githubusercontent.com/14920004/78912950-eee3b080-7a90-11ea-8505-b54edef9fc74.png)

**Comment by ASELSTM** [comment]
Hi @vilesovds,

Thank you for reporting this issue. It will be forwarded to our development teams. I will let you updated as soon as they provide me with their feedback. Thank you for your patience.

With regards,

**Comment by ASELSTM** [comment]
Hi @vilesovds,

Our development teams confirmed the issue you pointed out.  As a fix, they propose you to add the else case described above :
```
  else
  {
    /* Update ADC state machine to error */
    SET_BIT(hadc->State, HAL_ADC_STATE_ERROR_INTERNAL);
    
    /* Set ADC error code to ADC IP internal error */
    SET_BIT(hadc->ErrorCode, HAL_ADC_ERROR_INTERNAL);
  }

```
 in the following functions : 

- ` HAL_ADC_Start()` line [805](https://github.com/STMicroelectronics/stm32f2xx_hal_driver/blob/6e95e5668f6a8900ecb073db847ff71898bde799/Src/stm32f2xx_hal_adc.c#L805)

- `HAL_ADC_Start_IT()` line [1099](https://github.com/STMicroelectronics/stm32f2xx_hal_driver/blob/6e95e5668f6a8900ecb073db847ff71898bde799/Src/stm32f2xx_hal_adc.c#L1099)
- `HAL_ADC_Start_DMA()` line [1419 ](https://github.com/STMicroelectronics/stm32f2xx_hal_driver/blob/6e95e5668f6a8900ecb073db847ff71898bde799/Src/stm32f2xx_hal_adc.c#L1419)
- `HAL_ADCEx_InjectedStart()` line [205](https://github.com/STMicroelectronics/stm32f2xx_hal_driver/blob/6e95e5668f6a8900ecb073db847ff71898bde799/Src/stm32f2xx_hal_adc_ex.c#L225)

- `HAL_ADCEx_InjectedStart_IT()` line [317](https://github.com/STMicroelectronics/stm32f2xx_hal_driver/blob/6e95e5668f6a8900ecb073db847ff71898bde799/Src/stm32f2xx_hal_adc_ex.c#L317)

- ` HAL_ADCEx_MultiModeStart_DMA()` line [670 ](https://github.com/STMicroelectronics/stm32f2xx_hal_driver/blob/6e95e5668f6a8900ecb073db847ff71898bde799/Src/stm32f2xx_hal_adc_ex.c#L670)


This will be fixed and made available in a future firmware package release. Thank you once more for your contribution. 


With regards,

**Comment by ASELSTM** [comment]
ST Internal Reference:  85500

**Comment by ASELSTM** [comment]
Hi @vilesovds,

I hope you are fine. The issue you reported has been fixed, so please allow me then to close this thread. 
Thank you again for having reported.

With regards,
