### ISSUE TITLE
Constant interrupts during 2nd byte of 2 or 3 byte I2C receive. 

### ISSUE THREAD

**Issue by Arild-Ver** [STMicroelectronics/stm32f2xx_hal_driver#2]
STM32F205VBT6, stm32f2xx_hal_i2c.c: HAL_I2C_EV_IRQHandler and I2C_MasterReceive_RXNE

When receiving byte 2 out of a 2 or 3 byte receive using HAL_I2C_Master_Receive_IT, there is a storm interrupts. The following picture of of a series of transmissions with a slave. Green is SDA, yellow is SCL, and red is a GPIO set to high when HAL_I2C_EV_IRQHandler is called, and low when it returns. The second transmission is a 2 byte receive, with the interrupt storm highlighted. This is not from a minimal example, additional interrupts with higher priority are firing. 
![SDA_SCL_INT_WITHOUT_FIXpng](https://user-images.githubusercontent.com/86243109/122772919-2579a580-d2a8-11eb-86ee-d31ad631ce3f.png)

When starting the transmission, ITBUFEN is set, and hi2c->XferCount = 2/3. After the first byte is received, RXNE is set, generating an interrupt. HAL_I2C_EV_IRQHandler calls I2C_MasterReceive_RXNE. When the total tranmission is 2 or 3 bytes, this enters into the final, empty, else case and returns with no change. The flags are still set, and a new interrupt is generated. This continues until a second byte has been received, where BTF is set and I2C_MasterReceive_BTF is called instead of I2C_MasterReceive_RXNE. For a 2 byte receive, this is the end and the callback is called. For a 3 byte receive ITBUFEN is cleared and 1 byte read, preventing further interrupt spamming.

My suggested fix is to add `__HAL_I2C_DISABLE_IT(hi2c, I2C_IT_BUF);` to the final else in I2C_MasterReceive_RXNE. With that fix, only a single interrupt is generated for the second byte. 
![SDA_SCL_INT_WITH_FIXpng](https://user-images.githubusercontent.com/86243109/122773621-ca947e00-d2a8-11eb-8d14-be35b65e2022.png)
```

**Comment by ALABSTM** [comment]
Hi @Arild-Ver,

Thank you for this detailed report and the clarifying screenshots. Our development teams confirmed the point. It will be logged into our internal database and a fix will be made available soon hopefully.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 114158

**Comment by ALABSTM** [comment]
Fixed in commit 8b0bf71783d6f871e30d173295728f5edfc9755a
