### ISSUE TITLE
Signature for HAL_Delay in F2 produces a warning when compiled with C++20

### ISSUE THREAD

**Issue by kmholtan** [STMicroelectronics/stm32f2xx_hal_driver#3]
The signature for HAL_Delay in the STM32f2xx_hal_driver is:

`__weak void HAL_Delay(__IO uint32_t Delay)`

This is different from the signatures for the other architectures I've checked (like H7, F7, F1 and G4) where the __IO part is removed (i.e. volatile).

The lack of consistency in the signature is far from ideal in it self, but it becomes an issue with C++ 20 where it produces the warning:

warning: 'volatile'-qualified parameter is deprecated [-Wvolatile]
(See: https://godbolt.org/z/3nnranYzq for an example)

I propose to make the signature the same as for the other architectures I've checked:

`__weak void HAL_Delay(uint32_t Delay)`

**Comment by TOUNSTM** [comment]
ST Internal Reference: 161850

**Comment by TOUNSTM** [comment]
ST Internal Reference: 107263

**Comment by TOUNSTM** [comment]
See also [STM32CubeWB#22](https://github.com/STMicroelectronics/STM32CubeWB/issues/22).

**Comment by TOUNSTM** [comment]
See also [STM32CubeF0#11](https://github.com/STMicroelectronics/STM32CubeF0/issues/11).

**Comment by TOUNSTM** [comment]
Fixed in https://github.com/STMicroelectronics/stm32f2xx_hal_driver/commit/ee1fdd91b51a9bfc4eefa0f6421b47fb15f804f9
